export const UPDATE_JOB_DETAIL = 'UPDATE_JOB_DETAIL';
export const UPDATE_JOB_DETAIL_SUCCESS = 'UPDATE_JOB_DETAIL_SUCCESS';
export const UPDATE_JOB_DETAIL_FAILURE = 'UPDATE_JOB_DETAIL_FAILURE';
export const UPDATE_JOB_DETAIL_COMPLETED = 'UPDATE_JOB_DETAIL_COMPLETED';
